# Generated by Django 5.2.15 on 2026-08-23 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0008_propertygroup_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorization_sent", "Authorization Sent"),
                            ("authorized", "Authorized"),
                            ("under_review", "Under Review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("token_expires_at", models.DateTimeField()),
                ("authorization_sent_at", models.DateTimeField(blank=True, null=True)),
                ("authorized_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("review_note", models.TextField(blank=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_verifications_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="properties.propertysubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyVerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("authorization_letter", "Authorization Letter"),
                            ("ownership_document", "Ownership Document"),
                            ("lawyer_document", "Lawyer Document"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("public_id", models.CharField(max_length=500, unique=True)),
                ("secure_url", models.URLField(max_length=1000)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("uploaded_by_name", models.CharField(blank=True, max_length=255)),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="property_verification.propertyverification",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationRepresentative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("landlord", "Landlord"),
                            ("lawyer", "Lawyer"),
                            ("estate_manager", "Estate Manager"),
                            ("authorized_representative", "Authorized Representative"),
                        ],
                        max_length=40,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("organization_name", models.CharField(blank=True, max_length=255)),
                ("confirmed_identity", models.BooleanField(default=False)),
                ("confirmed_authority", models.BooleanField(default=False)),
                (
                    "verification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representative",
                        to="property_verification.propertyverification",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="propertyverification",
            index=models.Index(
                fields=["status", "-created_at"], name="prop_ver_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyverification",
            index=models.Index(
                fields=["token_expires_at"], name="prop_ver_token_expiry_idx"
            ),
        ),
    ]
