# Generated by Django 5.2.15 on 2026-08-23 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property_verification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyverification",
            name="email_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="propertyverification",
            name="email_provider_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="propertyverification",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propertyverification",
            name="email_status",
            field=models.CharField(
                choices=[
                    ("not_sent", "Not Sent"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="not_sent",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="propertyverification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("authorization_sent", "Authorization Sent"),
                    ("authorized", "Authorized"),
                    ("under_review", "Under Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("representative_responded", "Representative Responded"),
                    ("documents_submitted", "Documents Submitted"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PropertyVerificationAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("authorized", "Authorized"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("availability_confirmed", models.BooleanField(default=False)),
                ("agent_authorized", models.BooleanField(default=False)),
                ("authorization_note", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "verification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization",
                        to="property_verification.propertyverification",
                    ),
                ),
            ],
            options={
                "ordering": ["-responded_at"],
                "indexes": [
                    models.Index(
                        fields=["decision", "-responded_at"],
                        name="prop_auth_decision_idx",
                    )
                ],
            },
        ),
    ]
