# Generated by Django 5.2.15 on 2026-09-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_verification', '0002_propertyverification_email_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('authorization_sent', 'Authorization Sent'), ('authorized', 'Authorized'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30),
        ),
    ]
