# =====================================================
# SUCCESS CODES
# =====================================================

SUCCESS = "SUCCESS"

USER_REGISTERED = "USER_REGISTERED"
REGISTRATION_SUCCESS_OTP_SENT = "REGISTRATION_SUCCESS_OTP_SENT"

EMAIL_VERIFIED = "EMAIL_VERIFIED"

OTP_RESENT = "OTP_RESENT"

LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"

LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL"

LOGIN_FAILED = "LOGIN_FAILED"

PROFILE_UPDATED = "PROFILE_UPDATED"

PROFILE_RETRIEVED = "PROFILE_RETRIEVED"

PASSWORD_CHANGED = "PASSWORD_CHANGED"

PROPERTY_CREATED = "PROPERTY_CREATED"

PROPERTY_UPDATED = "PROPERTY_UPDATED"

BOOKING_CREATED = "BOOKING_CREATED"

PAYMENT_INITIALIZED = "PAYMENT_INITIALIZED"

WALLET_RETRIEVED = "WALLET_RETRIEVED"

WITHDRAWAL_REQUEST_CREATED = "WITHDRAWAL_REQUEST_CREATED"

KYC_SUBMITTED = "KYC_SUBMITTED"

# =====================================================
# ERROR CODES
# =====================================================

VALIDATION_ERROR = "VALIDATION_ERROR"

USER_NOT_FOUND = "USER_NOT_FOUND"

INVALID_CREDENTIALS = "INVALID_CREDENTIALS"

ACCOUNT_NOT_VERIFIED = "ACCOUNT_NOT_VERIFIED"

ACCOUNT_ALREADY_VERIFIED = "ACCOUNT_ALREADY_VERIFIED"

ACCOUNT_DISABLED = "ACCOUNT_DISABLED"

INVALID_OTP = "INVALID_OTP"

OTP_EXPIRED = "OTP_EXPIRED"

OTP_REQUIRED = "OTP_REQUIRED"

EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

PHONE_ALREADY_EXISTS = "PHONE_ALREADY_EXISTS"

PERMISSION_DENIED = "PERMISSION_DENIED"

UNAUTHORIZED = "UNAUTHORIZED"

NOT_FOUND = "NOT_FOUND"

SERVER_ERROR = "SERVER_ERROR"
