# Generated by Django 5.2.15 on 2026-08-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_type',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('property_moderator', 'Property Moderator'), ('finance_admin', 'Finance Admin'), ('support_admin', 'Support Admin'), ('operations_admin', 'Operations Admin')], db_index=True, max_length=40, null=True),
        ),
    ]
