# Generated by Django 5.2.15 on 2026-06-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agentprofile_landlordprofile_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='otp',
            new_name='email_otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='max_otp_sent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_used',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
