# Generated by Django 5.2.15 on 2026-08-02 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_alter_area_lga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Amenity Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FurnishingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Furnishing Status',
                'verbose_name_plural': 'Furnishing Statuses',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Property Condition',
                'verbose_name_plural': 'Property Conditions',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('allow_viewing_booking', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amenities', to='properties.amenitycategory')),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('agent', 'Agent'), ('landlord', 'Landlord'), ('admin', 'Admin')], editable=False, max_length=30)),
                ('size_unit', models.CharField(choices=[('sqm', 'Square Metres'), ('sqft', 'Square Feet'), ('acres', 'Acres'), ('hectares', 'Hectares'), ('plots', 'Plots')], default='sqm', max_length=20)),
                ('land_size', models.DecimalField(blank=True, decimal_places=2, help_text='Land size expressed in the selected unit.', max_digits=12, null=True)),
                ('building_size', models.DecimalField(blank=True, decimal_places=2, help_text='Building or floor size expressed in the selected unit.', max_digits=12, null=True)),
                ('payment_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually'), ('one_time', 'One Time')], default='annually', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('landmark', models.CharField(blank=True, help_text='Private address. Not shown publicly before booking.', max_length=255)),
                ('street_address', models.CharField(blank=True, help_text='Private address. Not shown publicly before booking.', max_length=255, null=True)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('toilets', models.PositiveIntegerField(default=0)),
                ('parking_spaces', models.PositiveIntegerField(default=0)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('caution_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('legal_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('agency_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('duplicate_found', 'Duplicate Found'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('more_information_required', 'More Information Required')], db_index=True, default='draft', max_length=40)),
                ('duplicate_similarity_score', models.DecimalField(blank=True, decimal_places=2, help_text='Similarity percentage between 0 and 100.', max_digits=5, null=True)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('floors', models.PositiveIntegerField(default=0)),
                ('units_available', models.PositiveIntegerField(default=1)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('is_new_build', models.BooleanField(default=False)),
                ('is_serviced', models.BooleanField(default=False)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('minimum_stay', models.PositiveIntegerField(blank=True, help_text='Minimum stay measured using the payment frequency.', null=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='property_submissions', to='properties.amenity')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_records', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_submissions', to='locations.area')),
                ('furnishing_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='properties.furnishingstatus')),
                ('property_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='properties.propertycondition')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='properties.propertypurpose')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_property_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_submissions', to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='properties.propertytype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_amenity_per_category'),
        ),
        migrations.AddIndex(
            model_name='propertysubmission',
            index=models.Index(fields=['status', '-created_at'], name='submission_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='propertysubmission',
            index=models.Index(fields=['submitted_by', 'status'], name='submission_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='propertysubmission',
            index=models.Index(fields=['area', 'property_type', 'purpose', 'bedrooms'], name='sub_duplicate_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('duplicate_similarity_score__isnull', True), models.Q(('duplicate_similarity_score__gte', 0), ('duplicate_similarity_score__lte', 100)), _connector='OR'), name='submission_similarity_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='propertysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('proposed_price__isnull', True), ('proposed_price__gte', 0), _connector='OR'), name='submission_proposed_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='propertysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('service_charge__gte', 0)), name='submission_service_charge_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='propertysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('caution_fee__gte', 0)), name='submission_caution_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='propertysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('legal_fee__gte', 0)), name='submission_legal_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='propertysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('agency_fee__gte', 0)), name='submission_agency_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='propertysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('land_size__isnull', True), ('land_size__gte', 0), _connector='OR'), name='submission_land_size_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='propertysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('building_size__isnull', True), ('building_size__gte', 0), _connector='OR'), name='submission_building_size_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='propertysubmission',
            constraint=models.CheckConstraint(condition=models.Q(('year_built__isnull', True), ('year_built__gte', 1800), _connector='OR'), name='submission_year_built_reasonable_minimum'),
        ),
    ]
