# Generated by Django 5.2.15 on 2026-08-05 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySubmissionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], db_index=True, max_length=20)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=20)),
                ('public_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('asset_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('secure_url', models.URLField(max_length=1000)),
                ('resource_type', models.CharField(max_length=30)),
                ('file_format', models.CharField(blank=True, max_length=30)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, help_text='Video duration in seconds.', max_digits=10, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Accessible description of the image.', max_length=255)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_cover', models.BooleanField(db_index=True, default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='properties.propertysubmission')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['submission', 'media_type'], name='sub_media_type_idx'), models.Index(fields=['submission', 'display_order'], name='sub_media_order_idx'), models.Index(fields=['submission', 'upload_status'], name='sub_media_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True), ('media_type', 'image')), fields=('submission',), name='one_cover_image_per_submission')],
            },
        ),
    ]
