# Generated by Django 5.2.15 on 2026-08-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertysubmissionmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('duplicate_found', 'Duplicate Found'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('more_information_required', 'More Information Required')], db_index=True, default='draft', max_length=40),
        ),
    ]
