# Generated by Django 5.2.15 on 2026-08-09 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_area_lga'),
        ('properties', '0003_alter_propertysubmission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('standalone_house', 'Standalone House'), ('apartment', 'Apartment'), ('estate_property', 'Estate Property'), ('room', 'Room'), ('commercial', 'Commercial Property'), ('land', 'Land')], db_index=True, max_length=40)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('building_identifier', models.CharField(blank=True, help_text='Building, block, tower or structure identifier used when identifying the physical property.', max_length=100)),
                ('unit_identifier', models.CharField(blank=True, help_text='Flat, apartment, room, shop, suite or unit identifier.', max_length=100)),
                ('house_number', models.CharField(blank=True, max_length=50)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('toilets', models.PositiveIntegerField(default=0)),
                ('parking_spaces', models.PositiveIntegerField(default=0)),
                ('floors', models.PositiveIntegerField(default=0)),
                ('units_available', models.PositiveIntegerField(default=1)),
                ('size_unit', models.CharField(choices=[('sqm', 'Square Metres'), ('sqft', 'Square Feet'), ('acres', 'Acres'), ('hectares', 'Hectares'), ('plots', 'Plots')], default='sqm', max_length=20)),
                ('land_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('building_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('is_new_build', models.BooleanField(default=False)),
                ('is_serviced', models.BooleanField(default=False)),
                ('amenities', models.ManyToManyField(blank=True, related_name='property_groups', to='properties.amenity')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_records', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_groups', to='locations.area')),
                ('furnishing_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_groups', to='properties.furnishingstatus')),
                ('property_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_groups', to='properties.propertycondition')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_groups', to='properties.propertytype')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_groups', to='properties.propertypurpose')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'area', 'property_type'], name='property_group_cat_area_idx'), models.Index(fields=['area', 'property_type', 'purpose', 'bedrooms'], name='property_group_id_idx')],
            },
        ),
    ]
