# Generated by Django 5.2.15 on 2026-08-09 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertygroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_frequency', models.CharField(blank=True, max_length=20)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('caution_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('legal_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('agency_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('minimum_stay', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('inspection_enabled', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_representations', to=settings.AUTH_USER_MODEL)),
                ('property_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='properties.propertygroup')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='representation', to='properties.propertysubmission')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property_group', 'status'], name='property_repr_pro_status_idx'), models.Index(fields=['agent', 'status'], name='property_repr_agent_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('property_group', 'agent'), name='unique_property_group_agent')],
            },
        ),
    ]
