# Generated by Django 5.2.15 on 2026-08-09 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyrepresentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysubmission',
            name='property_group',
            field=models.ForeignKey(blank=True, help_text='Canonical physical property this submission belongs to. Multiple submissions may reference the same property group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='properties.propertygroup'),
        ),
    ]
