# Generated by Django 5.2.15 on 2026-08-09 23:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertysubmission_property_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('similarity_score', models.DecimalField(decimal_places=2, help_text='Overall duplicate similarity score from 0 to 100.', max_digits=5)),
                ('matching_signals', models.JSONField(blank=True, default=dict, help_text='Individual signals that contributed to the similarity score.')),
                ('conflicts', models.JSONField(blank=True, default=list, help_text='Important differences found between the submission and the existing property.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('matched', 'Matched'), ('rejected', 'Rejected'), ('ignored', 'Ignored')], db_index=True, default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('property_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates', to='properties.propertygroup')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_property_duplicates', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates', to='properties.propertysubmission')),
            ],
            options={
                'ordering': ['-similarity_score', '-created_at'],
                'indexes': [models.Index(fields=['submission', 'status'], name='dup_candidate_submission_idx'), models.Index(fields=['property_group', 'status'], name='dup_candidate_property_idx'), models.Index(fields=['status', '-similarity_score'], name='dup_candidate_review_idx')],
                'constraints': [models.UniqueConstraint(fields=('submission', 'property_group'), name='unique_submission_duplicate_candidate'), models.CheckConstraint(condition=models.Q(('similarity_score__gte', 0), ('similarity_score__lte', 100)), name='dup_candidate_score_0_100')],
            },
        ),
    ]
