# Generated by Django 5.2.15 on 2026-08-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_propertyduplicatecandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertygroup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='inactive', max_length=20),
        ),
    ]
