# Generated by Django 5.2.15 on 2026-09-01 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertyeligibilityquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEligibilityAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('passed', 'Passed'), ('failed', 'Failed')], db_index=True, default='in_progress', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('evaluation_note', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_eligibility_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='properties.propertyeligibilitytest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyEligibilityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField(blank=True)),
                ('selected_options', models.JSONField(blank=True, default=list)),
                ('answer_number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('answer_date', models.DateField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='properties.propertyeligibilityquestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='properties.propertyeligibilityattempt')),
            ],
            options={
                'ordering': ['question__display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='propertyeligibilityattempt',
            index=models.Index(fields=['tenant', 'status'], name='elig_attempt_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyeligibilityattempt',
            index=models.Index(fields=['test', 'status'], name='elig_attempt_test_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyeligibilityattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('test', 'tenant'), name='one_active_attempt_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='propertyeligibilityanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_answer'),
        ),
    ]
