# Generated by Django 5.2.15 on 2026-09-02 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_propertyeligibilityattempt_propertyeligibilityanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_text', models.CharField(blank=True, max_length=255)),
                ('minimum_number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('minimum_date', models.DateField(blank=True, null=True)),
                ('maximum_date', models.DateField(blank=True, null=True)),
                ('accepted_options', models.JSONField(blank=True, default=list)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='properties.propertyeligibilityquestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
