# Generated by Django 5.2.15 on 2026-07-25 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "locations",
            "0002_alter_area_slug_alter_country_slug_alter_lga_slug_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="lga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="areas",
                to="locations.lga",
            ),
        ),
    ]
